name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

# 👇 give the default GITHUB_TOKEN the scopes it needs
permissions:
  contents: read           # still needed so the job can fetch code
  issues: write            # PR comments are Issues comments under the hood
  pull-requests: write     # good practice – covers reviews, labels, etc.

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/src
      ITERATIVE_DO_NOT_TRACK: 1          # disable CML telemetry

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with: { python-version: "3.10" }

      - uses: actions/setup-node@v3
        with: { node-version: "18" }

      - name: Install CML 0.20.5
        run: npm install -g @dvcorg/cml@0.20.5

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests ➜ JUnit
        run: |
          pytest --maxfail=1 --disable-warnings --capture=no \
                 --junitxml=test-results.xml

      - name: Build Markdown report
        run: |
          { echo '# Test Results'
            echo
            echo '```xml'
            cat test-results.xml
            echo '```'; } > report.md

      - name: Publish report as PR comment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # CML looks for REPO_TOKEN first
        run: cml comment create report.md
