name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/src
      # makes absolutely sure telemetry is off even if someone bumps CML later
      ITERATIVE_DO_NOT_TRACK: 1

    steps:
      # ─── Code ──────────────────────────────────────────────────────
      - uses: actions/checkout@v3

      # ─── Python ───────────────────────────────────────────────────
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # ─── Node + CML 0.20.5 (GOOD) ─────────────────────────────────
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install CML 0.20.5
        run: npm install -g @dvcorg/cml@0.20.5

      # ─── Project deps ─────────────────────────────────────────────
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ─── Tests ────────────────────────────────────────────────────
      - name: Run tests and save JUnit XML
        run: |
          pytest --maxfail=1 --disable-warnings --capture=no \
                 --junitxml=test-results.xml

      # ─── Build report (no quoting surprises) ──────────────────────
      - name: Build Markdown report
        run: |
          {
            echo '# Test Results'
            echo
            echo '```xml'
            cat test-results.xml
            echo '```'
          } > report.md

      # ─── Publish with CML CLI 0.20.5 ──────────────────────────────
      - name: Publish CML report as PR comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cml comment create report.md   # ‘comment create’ is equivalent to ‘report create’
